# CSV 파일 읽고 컬럼별 최고값과, 값의 개수 출력 max(), value_counts()

In [ ]:
import pandas as pd

In [ ]:
DIR_NAME = '../DATA/'
FILE_NAME = DIR_NAME + 'iris2.csv'
irisDF = pd.read_csv(FILE_NAME, header=None)
irisDF

       0    1    2    3               4
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
# irisDF.max()
irisDF.describe().loc['max']

0    7.9
1    4.4
2    6.9
3    2.5
Name: max, dtype: float64

In [ ]:
irisDF.count()

0    147
1    150
2    150
3    150
4    150
dtype: int64

In [ ]:
# staticDF = irisDF.describe()
staticDF

                0           1           2           3
count  147.000000  150.000000  150.000000  150.000000
mean     5.854422    3.054000    3.758667    1.198667
std      0.831094    0.433594    1.764420    0.763161
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.350000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000

In [ ]:
# staticDF.loc['25%']

0    5.1
1    2.8
2    1.6
3    0.3
Name: 25%, dtype: float64

In [ ]:
# irisDF.mean(numeric_only=True)

0    5.854422
1    3.054000
2    3.758667
3    1.198667
dtype: float64

In [ ]:
# irisDF.median(numeric_only=True)

0    5.80
1    3.00
2    4.35
3    1.30
dtype: float64