## [실습]
- csv 파일 읽고 컬럼별 최고값과 값의 개수 출력

In [91]:
import pandas as pd

DIR_PATH='../Data/'
FILE_NAME=DIR_PATH+'iris2.csv'
irisDF=pd.read_csv(FILE_NAME,header=None)#이 데이터에 헤더가 없다고 알려줌, sep=','< 기본
irisDF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       149 non-null    float64
 1   1       149 non-null    float64
 2   2       149 non-null    float64
 3   3       150 non-null    float64
 4   4       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [161]:
#최대값
reirisDF=irisDF.iloc[:,:4]
reirisDF=pd.DataFrame(reirisDF.max())
reirisDF.columns=['max']
reirisDF

   max
0  7.9
1  4.4
2  6.9
3  2.5

In [163]:
#개수
reirisDF=pd.DataFrame([irisDF[0].count(), irisDF[1].count(), irisDF[2].count(), irisDF[3].count()])
reirisDF.columns=['count']
reirisDF

   count
0    149
1    149
2    149
3    150

In [176]:
# 값의 개수 => value_counts()
irisDF.columns
for i in irisDF.columns:
    print(f'{irisDF[i].value_counts(dropna=False)}\n')

5.0    10
6.3     9
5.1     8
5.7     8
6.7     8
5.5     7
6.4     7
5.8     7
6.0     6
6.1     6
5.6     6
5.4     6
4.9     6
4.8     5
6.5     5
6.2     4
7.7     4
6.9     4
4.6     4
5.2     4
5.9     3
7.2     3
4.4     3
6.8     3
6.6     2
4.7     2
7.6     1
7.4     1
7.3     1
7.0     1
7.1     1
5.3     1
4.3     1
NaN     1
4.5     1
7.9     1
Name: 0, dtype: int64

3.0    26
2.8    14
3.2    13
3.1    12
3.4    12
2.7     9
2.9     9
2.5     8
3.5     6
3.8     6
3.3     6
2.6     5
2.3     4
3.7     3
2.4     3
2.2     3
3.6     3
3.9     2
4.4     1
4.0     1
4.1     1
4.2     1
NaN     1
2.0     1
Name: 1, dtype: int64

1.5    14
1.4    12
4.5     8
5.1     8
1.6     7
1.3     7
5.6     6
4.7     5
4.9     5
4.0     5
4.2     4
5.0     4
4.8     4
1.7     4
4.4     4
5.8     3
3.9     3
6.1     3
5.5     3
5.7     3
4.6     3
5.4     2
5.3     2
4.1     2
6.7     2
5.9     2
6.0     2
4.3     2
3.5     2
3.3     2
1.9     2
1.2     2
5.2     2
3.0     1
3.7     1
3.8     1
NaN     1
3.6     1
6.6     1
6.3     1
1.0     1
6.9     1
6.4     1
1.1     1
Name: 2, dtype: int64

0.2    28
1.3    13
1.8    12
1.5    12
1.4     8
2.3     8
1.0     7
0.4     7
0.3     7
0.1     6
2.1     6
2.0     6
1.2     5
1.9     5
1.6     4
2.5     3
2.2     3
2.4     3
1.1     3
1.7     2
0.6     1
0.5     1
Name: 3, dtype: int64

Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: 4, dtype: int64