# 1. ‘남북한발전전력량.xlsx’에서 아래 결과를 도출하세요.

## 1. DataFrame형식으로 데이터를 가져오세요.

In [15]:
import pandas as pd

DIR_PATH='../../Data/'

FILE_NAME= DIR_PATH +'남북한발전전력량.xlsx'

elecDF=pd.read_excel(FILE_NAME)

elecDF

,전력량 (억㎾h),발전 전력별,1990,1991,1992,1993,1994,1995,1996,1997,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
0,남한,합계,1077,1186,1310,1444,1650,1847,2055,2244,...,4031,4224,4336,4747,4969,5096,5171,5220,5281,5404
1,NaN,수력,64,51,49,60,41,55,52,54,...,50,56,56,65,78,77,84,78,58,66
2,NaN,화력,484,573,696,803,1022,1122,1264,1420,...,2551,2658,2802,3196,3343,3430,3581,3427,3402,3523
3,NaN,원자력,529,563,565,581,587,670,739,771,...,1429,1510,1478,1486,1547,1503,1388,1564,1648,1620
4,NaN,신재생,-,-,-,-,-,-,-,-,...,-,-,-,-,-,86,118,151,173,195
5,북한,합계,277,263,247,221,231,230,213,193,...,236,255,235,237,211,215,221,216,190,239
6,NaN,수력,156,150,142,133,138,142,125,107,...,133,141,125,134,132,135,139,130,100,128
7,NaN,화력,121,113,105,88,93,88,88,86,...,103,114,110,103,79,80,82,86,90,111
8,NaN,원자력,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-

## 2. 요약정보 출력해주세요.

In [19]:
elecDF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 29 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   전력량 (억㎾h)  2 non-null      object
 1   발전 전력별     9 non-null      object
 2   1990       9 non-null      object
 3   1991       9 non-null      object
 4   1992       9 non-null      object
 5   1993       9 non-null      object
 6   1994       9 non-null      object
 7   1995       9 non-null      object
 8   1996       9 non-null      object
 9   1997       9 non-null      object
 10  1998       9 non-null      object
 11  1999       9 non-null      object
 12  2000       9 non-null      object
 13  2001       9 non-null      object
 14  2002       9 non-null      object
 15  2003       9 non-null      object
 16  2004       9 non-null      object
 17  2005       9 non-null      object
 18  2006       9 non-null      object
 19  2007       9 non-null      object
 20  2008       9 non-null      object
 21  2009       9 non-null      object
 22  2010       9 non-null      object
 23  2011       9 non-null      object
 24  2012       9 non-null      object
 25  2013       9 non-null      object
 26  2014       9 non-null      object
 27  2015       9 non-null      object
 28  2016       9 non-null      object
dtypes: object(29)
memory usage: 2.2+ KB

## 3. 1990~2016 컬럼에서 컬럼별 최대값, 최소값을 출력해주세요.

In [17]:
elecDF.replace('-', None)

elecDF_1=elecDF.drop(['전력량 (억㎾h)','발전 전력별'] ,axis=1)
elecDF_1=elecDF_1.replace('-', None)

elecDF_1.max()

1990    1077
1991    1186
1992    1310
1993    1444
1994    1650
1995    1847
1996    2055
1997    2244
1998    2153
1999    2393
2000    2664
2001    2852
2002    3065
2003    3225
2004    3421
2005    3646
2006    3812
2007    4031
2008    4224
2009    4336
2010    4747
2011    4969
2012    5096
2013    5171
2014    5220
2015    5281
2016    5404
dtype: object

In [18]:
elecDF_1.min()

1990    64
1991    51
1992    49
1993    60
1994    41
1995    55
1996    52
1997    54
1998    61
1999    61
2000    56
2001    42
2002    53
2003    69
2004    59
2005    52
2006    52
2007    50
2008    56
2009    56
2010    65
2011    78
2012    77
2013    82
2014    78
2015    58
2016    66
dtype: object

## 4. 1990~2016 컬럼에서 짝수 컬럼 데이터만 출력해주세요.

In [21]:
elecDF_2=elecDF_1.iloc[:,::2]
elecDF_2

,1990,1992,1994,1996,1998,2000,2002,2004,2006,2008,2010,2012,2014,2016
0,1077,1310,1650,2055,2153,2664,3065,3421,3812,4224,4747,5096,5220,5404
1,64,49,41,52,61,56,53,59,52,56,65,77,78,66
2,484,696,1022,1264,1195,1518,1821,2056,2272,2658,3196,3430,3427,3523
3,529,565,587,739,897,1090,1191,1307,1487,1510,1486,1503,1564,1620
4,None,None,None,None,None,None,None,None,None,None,None,86,151,195
5,277,247,231,213,170,194,190,206,225,255,237,215,216,239
6,156,142,138,125,102,102,106,125,126,141,134,135,130,128
7,121,105,93,88,68,92,84,81,99,114,103,80,86,111
8,None,None,None,None,None,None,None,None,None,None,None,None,None,None

## 5. 전력량과 발전 전력별을 하나의 컬럼을 합치고 합친 걸럼을 추가해 주세요.

In [22]:
elecDF

elecDF['전력량 (억㎾h) + 발전 전력별'] = elecDF['전력량 (억㎾h)'] + '+' + elecDF['발전 전력별']
elecDF['전력량 (억㎾h) + 발전 전력별']

0    남한+합계
1      NaN
2      NaN
3      NaN
4      NaN
5    북한+합계
6      NaN
7      NaN
8      NaN
Name: 전력량 (억㎾h) + 발전 전력별, dtype: object

In [5]:
elecDF_m = pd.merge(elecDF['전력량 (억㎾h) + 발전 전력별'], elecDF)
elecDF_m

,전력량 (억㎾h) + 발전 전력별,전력량 (억㎾h),발전 전력별,1990,1991,1992,1993,1994,1995,1996,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
0,남한+합계,남한,합계,1077,1186,1310,1444,1650,1847,2055,...,4031,4224,4336,4747,4969,5096,5171,5220,5281,5404
1,NaN,NaN,수력,64,51,49,60,41,55,52,...,50,56,56,65,78,77,84,78,58,66
2,NaN,NaN,화력,484,573,696,803,1022,1122,1264,...,2551,2658,2802,3196,3343,3430,3581,3427,3402,3523
3,NaN,NaN,원자력,529,563,565,581,587,670,739,...,1429,1510,1478,1486,1547,1503,1388,1564,1648,1620
4,NaN,NaN,신재생,-,-,-,-,-,-,-,...,-,-,-,-,-,86,118,151,173,195
5,NaN,NaN,수력,156,150,142,133,138,142,125,...,133,141,125,134,132,135,139,130,100,128
6,NaN,NaN,화력,121,113,105,88,93,88,88,...,103,114,110,103,79,80,82,86,90,111
7,NaN,NaN,원자력,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
8,NaN,NaN,수력,64,51,49,60,41,55,52,...,50,56,56,65,78,77,84,78,58,66
9,NaN,NaN,화력,484,573,696,803,1022,1122,1264,...,2551,2658,2802,3196,3343,3430,3581,3427,3402,3523
10,NaN,NaN,원자력,529,563,565,581,587,670,739,...,1429,1510,1478,1486,1547,1503,1388,1564,1648,1620
11,NaN,NaN,신재생,-,-,-,-,-,-,-,...,-,-,-,-,-,86,118,151,173,195
12,NaN,NaN,수력,156,150,142,133,138,142,125,...,133,141,125,134,132,135,139,130,100,128
13,NaN,NaN,화력,121,113,105,88,93,88,88,...,103,114,110,103,79,80,82,86,90,111
14,NaN,NaN,원자력,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
15,NaN,NaN,수력,64,51,49,60,41,55,52,...,50,56,56,65,78,77,84,78,58,66
16,NaN,NaN,화력,484,573,696,803,1022,1122,1264,...,2551,2658,2802,3196,3343,3430,3581,3427,3402,3523
17,NaN,NaN,원자력,529,563,565,581,587,670,739,...,1429,1510,1478,1486,1547,1503,1388,1564,1648,1620
18,NaN,NaN,신재생,-,-,-,-,-,-,-,...,-,-,-,-,-,86,118,151,173,195
19,NaN,NaN,수력,156,150,142,133,138,142,125,...,133,141,125,134,132,135,139,130,100,128
20,NaN,NaN,화력,121,113,105,88,93,88,88,...,103,114,110,103,79,80,82,86,90,111
21,NaN,NaN,원자력,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
22,NaN,NaN,수력,64,51,49,60,41,55,52,...,50,56,56,65,78,77,84,78,58,66
23,NaN,NaN,화력,484,573,696,803,1022,1122,1264,...,2551,2658,2802,3196,3343,3430,3581,3427,3402,3523
24,NaN,NaN,원자력,529,563,565,581,587,670,739,...,1429,1510,1478,1486,1547,1503,1388,1564,1648,1620
25,NaN,NaN,신재생,-,-,-,-,-,-,-,...,-,-,-,-,-,86,118,151,173,195
26,NaN,NaN,수력,156,150,142,133,138,142,125,...,133,141,125,134,132,135,139,130,100,128
27,NaN,NaN,화력,121,113,105,88,93,88,88,...,103,114,110,103,79,80,82,86,90,111
28,NaN,NaN,원자력,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
29,NaN,NaN,수력,64,51,49,60,41,55,52,...,50,56,56,65,78,77,84,78,58,66
30,NaN,NaN,화력,484,573,696,803,1022,1122,1264,...,2551,2658,2802,3196,3343,3430,3581,3427,3402,3523
31,NaN,NaN,원자력,529,563,565,581,587,670,739,...,1429,1510,1478,1486,1547,1503,1388,1564,1648,1620
32,NaN,NaN,신재생,-,-,-,-,-,-,-,...,-,-,-,-,-,86,118,151,173,195
33,NaN,NaN,수력,156,150,142,133,138,142,125,...,133,141,125,134,132,135,139,130,100,128
34,NaN,NaN,화력,121,113,105,88,93,88,88,...,103,114,110,103,79,80,82,86,90,111
35,NaN,NaN,원자력,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
36,NaN,NaN,수력,64,51,49,60,41,55,52,...,50,56,56,65,78,77,84,78,58,66
37,NaN,NaN,화력,484,573,696,803,1022,1122,1264,...,2551,2658,2802,3196,3343,3430,3581,3427,3402,3523
38,NaN,NaN,원자력,529,563,565,581,587,670,739,...,1429,1510,1478,1486,1547,1503,1388,1564,1648,1620
39,NaN,NaN,신재생,-,-,-,-,-,-,-,...,-,-,-,-,-,86,118,151,173,195
40,NaN,NaN,수력,156,150,142,133,138,142,125,...,133,141,125,134,132,135,139,130,100,128
41,NaN,NaN,화력,121,113,105,88,93,88,88,...,103,114,110,103,79,80,82,86,90,111
42,NaN,NaN,원자력,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
43,NaN,NaN,수력,64,51,49,60,41,55,52,...,50,56,56,65,78,77,84,78,58,66
44,NaN,NaN,화력,484,573,696,803,1022,1122,1264,...,2551,2658,2802,3196,3343,3430,3581,3427,3402,3523
45,NaN,NaN,원자력,529,563,565,581,587,670,739,...,1429,1510,1478,1486,1547,1503,1388,1564,1648,1620
46,NaN,NaN,신재생,-,-,-,-,-,-,-,...,-,-,-,-,-,86,118,151,173,195
47,NaN,NaN,수력,156,150,142,133,138,142,125,...,133,141,125,134,132,135,139,130,100,128
48,NaN,NaN,화력,121,113,105,88,93,88,88,...,103,114,110,103,79,80,82,86,90,111
49,NaN,NaN,원자력,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
50,북한+합계,북한,합계,277,263,247,221,231,230,213,...,236,255,235,237,211,215,221,216,190,239

## 6. 5번에서 생성된 컬럼을 인덱스로 설정해 주세요.

In [15]:
elecDF_m.set_index('전력량 (억㎾h) + 발전 전력별', inplace=True)

KeyError: "None of ['전력량 (억㎾h) + 발전 전력별'] are in the columns"

In [17]:
elecDF_m

,전력량 (억㎾h),발전 전력별,1990,1991,1992,1993,1994,1995,1996,1997,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
전력량 (억㎾h) + 발전 전력별,,,,,,,,,,,,,,,,,,,,,
남한+합계,남한,합계,1077,1186,1310,1444,1650,1847,2055,2244,...,4031,4224,4336,4747,4969,5096,5171,5220,5281,5404
NaN,NaN,수력,64,51,49,60,41,55,52,54,...,50,56,56,65,78,77,84,78,58,66
NaN,NaN,화력,484,573,696,803,1022,1122,1264,1420,...,2551,2658,2802,3196,3343,3430,3581,3427,3402,3523
NaN,NaN,원자력,529,563,565,581,587,670,739,771,...,1429,1510,1478,1486,1547,1503,1388,1564,1648,1620
NaN,NaN,신재생,-,-,-,-,-,-,-,-,...,-,-,-,-,-,86,118,151,173,195
NaN,NaN,수력,156,150,142,133,138,142,125,107,...,133,141,125,134,132,135,139,130,100,128
NaN,NaN,화력,121,113,105,88,93,88,88,86,...,103,114,110,103,79,80,82,86,90,111
NaN,NaN,원자력,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
NaN,NaN,수력,64,51,49,60,41,55,52,54,...,50,56,56,65,78,77,84,78,58,66
NaN,NaN,화력,484,573,696,803,1022,1122,1264,1420,...,2551,2658,2802,3196,3343,3430,3581,3427,3402,3523
NaN,NaN,원자력,529,563,565,581,587,670,739,771,...,1429,1510,1478,1486,1547,1503,1388,1564,1648,1620
NaN,NaN,신재생,-,-,-,-,-,-,-,-,...,-,-,-,-,-,86,118,151,173,195
NaN,NaN,수력,156,150,142,133,138,142,125,107,...,133,141,125,134,132,135,139,130,100,128
NaN,NaN,화력,121,113,105,88,93,88,88,86,...,103,114,110,103,79,80,82,86,90,111
NaN,NaN,원자력,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
NaN,NaN,수력,64,51,49,60,41,55,52,54,...,50,56,56,65,78,77,84,78,58,66
NaN,NaN,화력,484,573,696,803,1022,1122,1264,1420,...,2551,2658,2802,3196,3343,3430,3581,3427,3402,3523
NaN,NaN,원자력,529,563,565,581,587,670,739,771,...,1429,1510,1478,1486,1547,1503,1388,1564,1648,1620
NaN,NaN,신재생,-,-,-,-,-,-,-,-,...,-,-,-,-,-,86,118,151,173,195
NaN,NaN,수력,156,150,142,133,138,142,125,107,...,133,141,125,134,132,135,139,130,100,128
NaN,NaN,화력,121,113,105,88,93,88,88,86,...,103,114,110,103,79,80,82,86,90,111
NaN,NaN,원자력,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
NaN,NaN,수력,64,51,49,60,41,55,52,54,...,50,56,56,65,78,77,84,78,58,66
NaN,NaN,화력,484,573,696,803,1022,1122,1264,1420,...,2551,2658,2802,3196,3343,3430,3581,3427,3402,3523
NaN,NaN,원자력,529,563,565,581,587,670,739,771,...,1429,1510,1478,1486,1547,1503,1388,1564,1648,1620
NaN,NaN,신재생,-,-,-,-,-,-,-,-,...,-,-,-,-,-,86,118,151,173,195
NaN,NaN,수력,156,150,142,133,138,142,125,107,...,133,141,125,134,132,135,139,130,100,128
NaN,NaN,화력,121,113,105,88,93,88,88,86,...,103,114,110,103,79,80,82,86,90,111
NaN,NaN,원자력,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
NaN,NaN,수력,64,51,49,60,41,55,52,54,...,50,56,56,65,78,77,84,78,58,66
NaN,NaN,화력,484,573,696,803,1022,1122,1264,1420,...,2551,2658,2802,3196,3343,3430,3581,3427,3402,3523
NaN,NaN,원자력,529,563,565,581,587,670,739,771,...,1429,1510,1478,1486,1547,1503,1388,1564,1648,1620
NaN,NaN,신재생,-,-,-,-,-,-,-,-,...,-,-,-,-,-,86,118,151,173,195
NaN,NaN,수력,156,150,142,133,138,142,125,107,...,133,141,125,134,132,135,139,130,100,128
NaN,NaN,화력,121,113,105,88,93,88,88,86,...,103,114,110,103,79,80,82,86,90,111
NaN,NaN,원자력,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
NaN,NaN,수력,64,51,49,60,41,55,52,54,...,50,56,56,65,78,77,84,78,58,66
NaN,NaN,화력,484,573,696,803,1022,1122,1264,1420,...,2551,2658,2802,3196,3343,3430,3581,3427,3402,3523
NaN,NaN,원자력,529,563,565,581,587,670,739,771,...,1429,1510,1478,1486,1547,1503,1388,1564,1648,1620
NaN,NaN,신재생,-,-,-,-,-,-,-,-,...,-,-,-,-,-,86,118,151,173,195
NaN,NaN,수력,156,150,142,133,138,142,125,107,...,133,141,125,134,132,135,139,130,100,128
NaN,NaN,화력,121,113,105,88,93,88,88,86,...,103,114,110,103,79,80,82,86,90,111
NaN,NaN,원자력,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
NaN,NaN,수력,64,51,49,60,41,55,52,54,...,50,56,56,65,78,77,84,78,58,66
NaN,NaN,화력,484,573,696,803,1022,1122,1264,1420,...,2551,2658,2802,3196,3343,3430,3581,3427,3402,3523
NaN,NaN,원자력,529,563,565,581,587,670,739,771,...,1429,1510,1478,1486,1547,1503,1388,1564,1648,1620
NaN,NaN,신재생,-,-,-,-,-,-,-,-,...,-,-,-,-,-,86,118,151,173,195
NaN,NaN,수력,156,150,142,133,138,142,125,107,...,133,141,125,134,132,135,139,130,100,128
NaN,NaN,화력,121,113,105,88,93,88,88,86,...,103,114,110,103,79,80,82,86,90,111
NaN,NaN,원자력,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
북한+합계,북한,합계,277,263,247,221,231,230,213,193,...,236,255,235,237,211,215,221,216,190,239

# 2. ‘iris.csv’에서 아래 결과를 도출하세요.

In [1]:
import pandas as pd

In [2]:
DIR_PATH='../../Data/'

FILE_NAME= DIR_PATH +'iris.csv'

irisDF=pd.read_csv(FILE_NAME)

irisDF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   SepalLength  150 non-null    float64
 1   SepalWidth   150 non-null    float64
 2   PetalLength  150 non-null    float64
 3   PetalWidth   150 non-null    float64
 4   Name         150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

## 1. Length 데이터만 추출해서 출력해주세요.

In [3]:
irisDF

irisDF[['SepalLength','PetalLength']]

     SepalLength  PetalLength
0            5.1          1.4
1            4.9          1.4
2            4.7          1.3
3            4.6          1.5
4            5.0          1.4
..           ...          ...
145          6.7          5.2
146          6.3          5.0
147          6.5          5.2
148          6.2          5.4
149          5.9          5.1

[150 rows x 2 columns]

## 2. SepalLength 컬럼에서 길이가 5.0보다 큰 걸럼의 SepalLength와 Names만 출력해주세요.

In [4]:
data_boolean=irisDF['SepalLength']>5.0

irisDF[data_boolean]['Name']

0         Iris-setosa
5         Iris-setosa
10        Iris-setosa
14        Iris-setosa
15        Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Name, Length: 118, dtype: object

## 3. Iris-setosa, Iris-versicolor, Iris-virginica에서 각각 최대, 최소 컬럼을 출력해 주세요.

In [6]:
irisDF[irisDF.Name=='Iris-setosa'].max()

SepalLength            5.8
SepalWidth             4.4
PetalLength            1.9
PetalWidth             0.6
Name           Iris-setosa
dtype: object

In [7]:
irisDF[irisDF.Name=='Iris-setosa'].min()

SepalLength            4.3
SepalWidth             2.3
PetalLength            1.0
PetalWidth             0.1
Name           Iris-setosa
dtype: object

In [8]:
irisDF[irisDF.Name=='Iris-versicolor'].max()

SepalLength                7.0
SepalWidth                 3.4
PetalLength                5.1
PetalWidth                 1.8
Name           Iris-versicolor
dtype: object

In [9]:
irisDF[irisDF.Name=='Iris-versicolor'].min()

SepalLength                4.9
SepalWidth                 2.0
PetalLength                3.0
PetalWidth                 1.0
Name           Iris-versicolor
dtype: object

In [10]:
irisDF[irisDF.Name=='Iris-virginica'].max()

SepalLength               7.9
SepalWidth                3.8
PetalLength               6.9
PetalWidth                2.5
Name           Iris-virginica
dtype: object

In [13]:
irisDF[irisDF.Name=='Iris-virginica'].min()

SepalLength               4.9
SepalWidth                2.2
PetalLength               4.5
PetalWidth                1.4
Name           Iris-virginica
dtype: object