# [실습] 

- CSV 파일을 읽고 컬럼별 최고값과 값의 개수 출력

In [ ]:
# 판다스 불러오기
import pandas as pd

# 파일 경로 및 이름 설정
DIR_PATH = '../Data/'
FILE_NAME = DIR_PATH + 'iris2.csv'

# 파일 데이터프레임화
# 데이터에 앞부분이 없으니 header 로 설정을 해줘야 한다.
# colunms 으로 header를 지정할 수 도 있습니다.
df_iris = pd.read_csv(FILE_NAME, header=None, na_values=0)

# 데이터 확인
df_iris

       0    1    2    3               4
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
df_iris.columns
len(df_iris.columns)

5

In [ ]:
# 컬럼별 최고값
for i in range(0, len(df_iris.columns)) :
    print(f'{i}컬럼의 최고값 :', df_iris[i].max())

0의 최고값 : 7.9
1의 최고값 : 4.4
2의 최고값 : 6.9
3의 최고값 : 2.5
4의 최고값 : Iris-virginica

In [ ]:
# 값의 갯수
for i in range(0, len(df_iris.columns)) :
    print(f'{i}컬럼값의 갯수 :\n', df_iris[i].value_counts())

0값의 갯수 :
 5.0    10
5.1     9
6.3     9
5.7     8
5.8     7
5.5     7
6.4     7
6.7     7
6.1     6
6.0     6
5.6     6
4.8     5
4.9     5
5.4     5
6.5     5
6.2     4
7.7     4
6.9     4
4.6     4
5.2     4
5.9     3
4.4     3
7.2     3
6.8     3
6.6     2
4.7     2
7.6     1
7.4     1
7.3     1
7.0     1
7.1     1
5.3     1
4.3     1
4.5     1
7.9     1
Name: 0, dtype: int64
1값의 갯수 :
 3.0    26
2.8    14
3.2    13
3.1    12
3.4    12
2.9    10
2.7     9
2.5     8
3.5     6
3.3     6
3.8     6
2.6     5
2.3     4
3.7     3
2.4     3
2.2     3
3.6     3
3.9     2
4.4     1
4.0     1
4.1     1
4.2     1
2.0     1
Name: 1, dtype: int64
2값의 갯수 :
 1.5    14
1.4    12
5.1     8
4.5     8
1.6     7
1.3     7
5.6     6
4.7     5
4.9     5
4.0     5
4.2     4
5.0     4
4.4     4
4.8     4
1.7     4
3.9     3
4.6     3
5.7     3
4.1     3
5.5     3
6.1     3
5.8     3
3.3     2
5.4     2
6.7     2
5.3     2
5.9     2
6.0     2
1.2     2
4.3     2
1.9     2
3.5     2
5.2     2
3.0     1
1.1     1
3.7     1
3.8     1
6.6     1
6.3     1
1.0     1
6.9     1
3.6     1
6.4     1
Name: 2, dtype: int64
3값의 갯수 :
 0.2    28
1.3    13
1.8    12
1.5    12
1.4     8
2.3     8
1.0     7
0.4     7
0.3     7
0.1     6
2.1     6
2.0     6
1.2     5
1.9     5
1.6     4
2.5     3
2.2     3
2.4     3
1.1     3
1.7     2
0.6     1
0.5     1
Name: 3, dtype: int64
4값의 갯수 :
 Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: 4, dtype: int64